### ISSUE TITLE
Noteの日本語訳について

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/analytics.ja-JP#1]
Noteの日本語訳について
URL
https://experienceleague.adobe.com/docs/analytics/analyze/reports-analytics/getting-started.html?lang=ja

日本語訳1
注：​この機能を使用するには、ブラウザーで cookie が有効になっている必要があります。コンピューターから cookie を削除した場合、除外 cookie を再び設定する必要があります。

日本語訳2

メモ

本製品は、北米および実際に販売されているその他の地域での販売が許可されています。 他の国や地域での販売に関する現地の要件を満たしていない場合があります。

「注」と「メモ」の2つの異なる翻訳があり、翻訳を一貫させる必要があります。
ちなみに　Adobe termdbの翻訳は「メモ」　です

![image](https://user-images.githubusercontent.com/2255096/151293188-2a4f2cac-d880-4b9a-8996-835ba9cd6d64.png)

**Comment by mak-adobe** [comment]
@yanlicao  フィードバックをありがとうございました。本件は AN-1234 として。。。。。。
