### ISSUE TITLE
計算指標テンプレート翻訳の語順

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/analytics.ja-JP#10]
Issue in ./help/analyze/analysis-workspace/components/apply-create-metrics.md

Current: 計算指標テンプレートは、使用可能なAdobeのリストに指標アイコンを表示します。
To Be: 計算指標テンプレートでは、使用可能なコンポーネントのリストに Adobe アイコンを表示します。

Original: Calculated metric templates show an Adobe icon in the list of available components.

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。G11N-12804のチケットで対応を開始しました。

**Comment by notakemu** [comment]
@mak-adobe さん、こちらも迅速なご対応ありがとうございます！

**Comment by mak-adobe** [comment]
@notakemu 修正が完了しました。ご協力ありがとうございました。
