### ISSUE TITLE
Mislead Japanese translation

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics.ja-JP#11]
Issue in ./help/analyze/analysis-workspace/components/data-dictionary/view-data-dictionary.md

English:
Shows components that are most commonly used with the component you are viewing.
Japanese:
表示しているコンポーネントで最も一般的に使用されるコンポーネントを表示します。

The following Japanese version is better.
表示しているコンポーネントと最も一緒に使用されるコンポーネントを表示します。

**Comment by mak-adobe** [comment]
@immany 修正が完了しました。ご協力ありがとうございました。
