### ISSUE TITLE
翻訳エラー: (metrics) 単一ページ訪問数 (この名称の変更)

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/analytics.ja-JP#13]
Issue in ./help/components/metrics/single-page-visits.md

[現在の翻訳] 単一ページ訪問数
[正しい翻訳] 直帰数
[原文] Single page visits

※こちらは，metrics (指標) 側のリクエストとなります。
　dimension 同様，翻訳自体は正しいのですが、Analytics UI (dimension, metrics) では，
　[Eng: single page visit] → [Jp: 直帰数]
　となっているため、UI と一致させるためにお願い致します

**Comment by mak-adobe** [comment]
@khagiwar G11N-13154 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@khagiwar 修正が完了しました。ご協力ありがとうございました。
