### ISSUE TITLE
Break down dimension should not be translated to "ディメンションの分類"

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics.ja-JP#14]
Issue in ./help/analyze/analysis-workspace/components/dimensions/t-breakdown-fa.md

In Analytics, "分類" is the translation for "Classification." We should not use this Japanese word for "break down/ breakdowns."

**Comment by jonsamhudec** [comment]
Actions tracked under G11N-16092.

**Comment by mak-adobe** [comment]
@immany 対応が見送りになったためクローズします。ありがとうございました。
