### ISSUE TITLE
Referrer should be translated to "リファラー"

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics.ja-JP#15]
Issue in ./help/components/dimensions/referrer.md

> 同じレポートに、Analysis Workspace と Data Warehouse で異なる結果が表示されます。Analysis Workspace は、内部 URL フィルターに一致する値を除き、個々のページの**_転送者_**を報告します。Data Warehouse は、訪問の最初の**_転送者_**のみを報告し、内部 URL フィルターを無視します。

Referrer should be translated to "リファラー"

**Comment by mak-adobe** [comment]
@immany お待たせいたしました。修正が完了しました。
