### ISSUE TITLE
Qualtrics plugin Error

### ISSUE THREAD

**Issue by mikobe2020** [AdobeDocs/analytics.ja-JP#17]
An error message will be displayed each time we access each document pages of Experience League.
This seems to be caused by the Qualtrics plugin.
It occur when the browser's language settings are set to a language other than English.

![image](https://github.com/AdobeDocs/analytics.ja-JP/assets/84787146/a6531048-3f95-438b-a0a0-8e4c773a0846)

![image](https://github.com/AdobeDocs/analytics.ja-JP/assets/84787146/12d9d919-7b43-4d88-959e-72e94f20efff)

**Comment by mak-adobe** [comment]
@mikobe2020 ありがとうございます。 G11N-15532 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@mikobe2020 修正が完了しました。ご確認お願いします。

**Comment by mikobe2020** [comment]
Hi mak,

Thank for your support.
I confirmed that the error message is no longer displayed.

However it may be a different issue, but it seems that sending feedback causes an error.
When I press the thumbs up button, an error message appears.
![image](https://github.com/AdobeDocs/analytics.ja-JP/assets/84787146/e40c39ee-ebe0-487b-a0f4-432e3ad618e1)

**Comment by mak-adobe** [comment]
@mikobe2020 ご確認ありがとうございます。こちらでも修正直後は同様にエラーが発生したのですが、キャッシュクリアした後は発生しなくなりました。念のためキャッシュクリアし、もう一度テストしていただけないでしょうか。直らない場合はOS、Browserのバージョンをお知らせください。
