### ISSUE TITLE
ピリオド (.) が期間と誤って翻訳されています

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/analytics.ja-JP#18]
Issue in ./help/admin/admin/c-manage-report-suites/c-edit-report-suites/general/internal-url-filter-admin.md

日本語訳: 一部のレポートスイートには、期間 (.) がデフォルトで設定されています。 
英語原文: Some report suites have an internal URL filter of a period (.) configured by default.

上記文脈では、period は「期間」ではなく「ピリオド」もしくは「終止符」と翻訳しないと意味が通じないと思います。

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。 G11N-15543 のチケットで対応を開始しました。

**Comment by notakemu** [comment]
@mak-adobe 早々に着手していただき、ありがとうございます。

**Comment by mak-adobe** [comment]
@notakemu 修正が完了しました。ご協力ありがとうございました。

**Comment by notakemu** [comment]
@mak-adobe ご対応ありがとうございました！
