### ISSUE TITLE
Line should be "折れ線" for Analytics 

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics.ja-JP#19]
Issue in ./help/analyze/analysis-workspace/visualizations/line.md
In the UI, the Line graph is shown as "折れ線." Hence, the document should be shown in the same way as the UI.

**Comment by mak-adobe** [comment]
@immany ありがとうございます。 G11N-16134 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@immany テキスト部分は修正が完了しました。画像の修正は未完了です。もう少しお待ちください。

**Comment by mak-adobe** [comment]
@immany 画像部分も修正が完了しました。ご協力ありがとうございました。
