### ISSUE TITLE
日本語のTOCが長すぎて完全に表示できません

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/analytics.ja-JP#2]
URL

https://experienceleague.adobe.com/docs/analytics/analyze/reports-analytics/getting-started.html?lang=ja
日本語のTOCが長すぎて完全に表示できません

右側の目次ナビゲーションバーを参照してください。

Experience Cloud を使用したロ....
ユーザーのアカウント設定の...

サイズ変更が不可能な場合は、代わりに文字列全体を表示するためのツールチップを表示することはいかがでしょうか。

**Comment by mak-adobe** [comment]
ありがとうございます。こちらの環境では再現できませんでした。お使いの環境についてご教示いただくことは可能でしょうか？

**Comment by yanlicao** [comment]
Mak-san
問題は現在のページで修正されていますが、他のページには引き続き表示されます。私はWindows10を使用していますが、問題はFFとIE、およびchomeで発生します。
page

https://experienceleague.adobe.com/docs/analytics/analyze/reports-analytics/t-running-report-types.html?lang=ja
screenshot: 
![image](https://user-images.githubusercontent.com/2255096/162676463-639d390f-1167-4724-8a6f-5329294f66ad.png)

**Comment by mak-adobe** [comment]
@yanlicao  当ヘルプページは、ブラウザの幅によってレイアウトが自動調整されるようにデザインされていますが、ブラウザの幅によっては右側のリンクが全て表示できず、「...」で省略表示されることがあります。
ブラウザの幅を少し広くするか、または狭くしていただくと、全て表示されるようになります。お試しください。

**Comment by yanlicao** [comment]
なるほど、承知致しました。
このチケットを閉じてください
ありがとうございます。
