### ISSUE TITLE
翻訳エラー: analytics data warehouse (sFTP 送信)

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/analytics.ja-JP#20]
Issue in ./help/export/ftp-and-sftp/c-sftp/ftp-sftp-dw.md

---------------
current Japanese: ポートレポートをリクエストする際には、Data Warehouse22 のみが使用されます。
---> suggestion Japanease: Data Warehouse レポートをリクエストする場合、ポート 22 だけが使用されます。

Eng: Only port 22 is used when requesting a Data Warehouse report.

**Comment by mak-adobe** [comment]
@khagiwar ポート22の修正は完了しましたが、他の不具合が見つかったので G11N-16198 のチケットを作成しました。もう少しお待ちください。

**Comment by mak-adobe** [comment]
@khagiwar 修正が全て完了しました。ご協力ありがとうございました。
