### ISSUE TITLE
「その他の要因」セクションのテーブルの「最適化」列内の誤訳

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/analytics.ja-JP#21]
Issue in ./help/analyze/analysis-workspace/workspace-faq/optimizing-performance.md

「その他の要因」セクションのテーブルの「最適化」列に、以下の誤訳があります。
1. 比較の翻訳が2箇所とも反対の意味に翻訳されている。
2. “contains any of” が "次のいずれかを含む" と翻訳されていない。（Analytics の UI では "次のいずれかを含む" と翻訳されています。）

（対象箇所）
日本語訳: 演算子を使用した場合、「次に等しい」よりも「次を含む」の方が速く、「次のいずれかと等しい」よりも「次のいずれかに等しい」の方が速くなります
Original (English): With operators, “equals” will be faster than “contains”, and “equals any of” will be faster than “contains any of”.

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。 G11N-16590 のチケットで対応を開始しました。

**Comment by notakemu** [comment]
@mak-adobe さん、早速対応を開始していただき、ありがとうございます！

**Comment by mak-adobe** [comment]
@notakemu 修正対応が完了し、本番ページへの反映を開始しました。もう少しお待ちください。

**Comment by notakemu** [comment]
@mak-adobe さん、ご連絡ありがとうございます。本番ページに変更が反映されていることを確認いたしました。ご対応ありがとうございました。
