### ISSUE TITLE
エクステンション購入に関する記述の誤訳

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/analytics.ja-JP#23]
Issue in ./help/technotes/data-retention.md

English: Extending data retention beyond the default retention period of 25 months requires the purchase of extensions, which are available in increments of one year each. Up to eight extensions can be purchased, for a total of 10 years 1 month (2 years 1 month for default retention, plus 8 years purchased).

日本語: デフォルトのデータ保持期間である 25 ヶ月を超えてデータを保持したい場合は、エクステンションを購入する必要があります。エクステンションは 1 年ごとに 1 回ご利用いただけます。エクステンションは最大 8 回購入でき、合計 10 年 1 ヶ月（デフォルトの 2 年 1 ヶ月 + 追加の 8 年）ご利用いただけます。

上記のエクステンション購入に関する記述の翻訳に誤りがあります。

誤「エクステンションは 1 年ごとに 1 回ご利用いただけます。エクステンションは最大 8 回購入でき」
正「エクステンションは 1 年単位でご購入いただけます。エクステンションは最大 8 つ購入でき」

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。 G11N-16791 のチケットで対応を開始しました。

**Comment by notakemu** [comment]
@mak-adobe さん、本件、修正が適用されたようです。迅速なご対応ありがとうございました。

**Comment by mak-adobe** [comment]
@notakemu 反映されましたね。ありがとうございました。
