### ISSUE TITLE
モバイル参照ディメンション ページ内の誤訳

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/analytics.ja-JP#24]
Issue in ./help/components/dimensions/mobile-dimensions.md

1. 
English: See Mobile lifecycle dimensions or Mobile lifecycle metrics for tracking within a mobile app.
日本語 (as-is): 詳しくは、 モバイルのライフサイクルディメンション または モバイルのライフサイクル指標 モバイルアプリ内での追跡用。
日本語 (to-be): モバイルアプリ内での追跡について、モバイルライフサイクルディメンション または モバイルライフサイクル指標 を参照してください。

2.
English: Mobile lookup dimensions provide insight around the properties of mobile devices that visit your site.
日本語 (as-is): モバイル参照 寸法 は、サイトを訪問したモバイルデバイスのプロパティに関するインサイトを提供します。
日本語 (to-be): モバイル参照 ディメンション は、サイトを訪問したモバイルデバイスのプロパティに関するインサイトを提供します。

3.
English: For the Mobile Carrier dimension, Adobe partners with Digital Element using NetAcuity to maintain lookups between IP address and mobile carrier.
日本語 (as-is): の 携帯電話会社 ディメンション、Adobeパートナー デジタル要素 NetAcuity を使用して、IP アドレスと携帯電話会社間の検索を維持する。
日本語 (to-be): 携帯電話会社 ディメンションについて、Adobe は Digital Element と提携して NetAcuity を使用し、IP アドレスと携帯電話会社間の参照を維持しています。

4. 
English: For all other mobile dimensions, Adobe partners with DeviceAtlas to maintain lookups between user agent and each respective mobile dimension.
日本語 (as-is): その他すべてのモバイルディメンションについて、Adobeパートナーは DeviceAtlas ユーザーエージェントと各モバイルディメンション間の検索を維持する。
日本語 (to-be): その他すべてのモバイルディメンションについて、Adobe は DeviceAtlas と提携して、ユーザーエージェントと各モバイルディメンション間の参照を維持しています。

5. 
English: For Web SDK implementations, enable Geo Lookup (for Mobile Carrier) or Device Lookup (for all other dimensions) when configuring a datastream.
日本語 (as-is): Web SDK 実装の場合、を有効にします。 地域ルックアップ （携帯電話会社の場合）または デバイス参照 （他のすべてのディメンションの場合） データストリームの設定.
日本語 (to-be): Web SDK 実装の場合、データストリームの設定 をするときに Geo Lookup （携帯電話会社の場合）または Device Lookup （他のすべてのディメンションの場合） を有効にします。

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。 G11N-16710 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@notakemu 修正が完了しました。ご確認お願いします。

**Comment by notakemu** [comment]
@mak-adobe さん、修正を確認いたしました。迅速なご対応ありがとうございました。
