### ISSUE TITLE
3点の誤訳

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/analytics.ja-JP#26]
Issue in ./help/components/metrics/pages-not-found.md

[Source] Pages not found
[Current] エラーページ（404）
[Expected] ページが見つかりません

[Source] The ‘Pages not found’
[Current] 「ページが見つかりませんでした
[Expected] 「ページが見つかりません」

[Source] Topics: Metrics
[Current] トピック：
[Expected]  トピック： 指標

**Comment by mak-adobe** [comment]
ありがとうございます。G11N-17548のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@notakemu まず指標名の修正が完了しました。「トピック： 指標」に関してはもう少々お待ちください。

**Comment by notakemu** [comment]
@mak-adobe 指標名の修正ありがとうございます。修正を確認いたしました。
「トピック： 指標」については承知いたしました。よろしくお願いいたします。

**Comment by notakemu** [comment]
@mak-adobe  「トピック： 指標」の修正を確認いたしました。ご対応ありがとうございました。
