### ISSUE TITLE
 https://experienceleague.adobe.com/docs/analytics/analyze/reports-analytics/getting-started.html?lang=ja ページ上のアイコンが大きすぎます

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/analytics.ja-JP#3]
https://experienceleague.adobe.com/docs/analytics/analyze/reports-analytics/getting-started.html?lang=ja  ページ上のアイコンが大きすぎます

1. URLをクリックします
 https://experienceleague.adobe.com/docs/analytics/analyze/reports-analytics/getting-started.html?lang=ja 

2.以下の文字を参照してください
Click the Account icon <icon> at the top right, then click the Account Settings (wheel) icon next to your login name.
右上のアカウント名アイコン  をクリックし、ログイン名の横にある「アカウントの設定」（車輪）をクリックします。

問題：アイコンが大きすぎます、可能であれば縮小できますか

![image](https://user-images.githubusercontent.com/2255096/151275404-7fd3a7bf-3acb-40ef-b4b6-051d4a370e8d.png)

**Comment by mak-adobe** [comment]
@yanlicao フィードバックをありがとうございました。修正を依頼しておりますので、少しお待ちください。AN-2345として登録。。。。。

**Comment by mak-adobe** [comment]
@yanlicao ご指摘いただいたページは、2023年12月31日に廃止予定の機能についての説明ページであり、該当のアイコンは現在は画面に表示されません。
最新の画面に表示される新しいExperience Cloudのヘッダの使い方については、以下のページを参照ください。
https://experienceleague.adobe.com/docs/core-services/interface/experience-cloud.html?lang=ja#preferences
