### ISSUE TITLE
jpページの翻訳、実際のUIと一致しない

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/analytics.ja-JP#4]
jpページの翻訳、実際のUIと一致しない
URL
https://experienceleague.adobe.com/docs/analytics/analyze/reports-analytics/getting-started.html?lang=ja#

以下の翻訳は実際のUIと一致しないため、修正する必要があります
会社の設定 -  実際のUIは　　 会社名　　です。

![image](https://user-images.githubusercontent.com/2255096/151275750-b6a6f286-aa66-4e47-b222-0bfdd66123a9.png)

![image](https://user-images.githubusercontent.com/2255096/151275694-f2aa2d82-ac02-4e4c-a5cc-69895c1a5608.png)

**Comment by mak-adobe** [comment]
@yanlicao ありがとうございます。チームへ対応を依頼中（G11N-9040）です。少しお待ちください。

**Comment by mak-adobe** [comment]
@yanlicao 修正が完了しました。ご協力ありがとうございました。
