### ISSUE TITLE
The name for "Visit number" dimension should be "通算訪問回数"

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics.ja-JP#7]
Issue in ./help/components/dimensions/visit-number.md

The dimension "Visit Number" shows as "通算訪問回数" on Japanese UI, to reduce the confusion, please update the document from "訪問数" to "通算訪問回数." Thanks.

**Comment by mak-adobe** [comment]
@immany  ご指摘ありがとうございます。担当部署へ対応を依頼（G11N-9144）しました。少しお待ちくださいませ。

**Comment by mak-adobe** [comment]
修正が完了しました。ご協力ありがとうございました。
