### ISSUE TITLE
Incorrect translation Japanese sentence: 'prop では大文字と小文字が区別されます。'

### ISSUE THREAD

**Issue by ashimizu-ccj** [AdobeDocs/analytics.ja-JP#8]
Issue in ./help/components/dimensions/prop.md
The original text explains 'You can make any prop case-sensitive.', but Japanese translation show wrong sentence as 'prop では大文字と小文字が区別されます。'. It should be 'prop では大文字と小文字を区別するように変更することができます。' for corresponding to original sentence.

**Comment by mak-adobe** [comment]
@ashimizu-ccj フィードバックをありがとうございます。担当部署へ対応を依頼（G11N-9146）しました。

**Comment by mak-adobe** [comment]
@ashimizu-ccj 修正が完了しました。ご協力ありがとうございました。
