### ISSUE TITLE
s_gi() 関数ページの翻訳の語順がおかしい

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/analytics.ja-JP#9]
Issue in ./help/implement/vars/functions/s-gi.md
![image](https://github.com/AdobeDocs/analytics.ja-JP/assets/15355919/e40ee78c-1cdb-40eb-a894-9f5a68c54db8)
![image](https://github.com/AdobeDocs/analytics.ja-JP/assets/15355919/04e57f7b-3e41-4514-8453-b5fbf0c73447)

**Comment by mak-adobe** [comment]
@notakemu ご報告ありがとうございます。不具合を確認しました。社内調整しますので少々お待ちください。

**Comment by mak-adobe** [comment]
@notakemu G11N-12803のチケットで対応を開始しました。

**Comment by notakemu** [comment]
@mak-adobe さん、迅速なご対応ありがとうございます！

**Comment by mak-adobe** [comment]
@notakemu 修正が完了しました。ご協力ありがとうございました。

**Comment by notakemu** [comment]
@mak-adobe さん、修正、ありがとうございました！
